version: 0.2

phases:
  install:
    commands:
      - npm i
  build:
    commands:
      - npm run tsc
      - aws cloudformation package
        --template-file samTemplate.yaml
        --s3-bucket "${S3_BUCKET}"
        --output-template-file outputSamTemplate.yaml

artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
